name: farcaster

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - beta

jobs:
  farcaster:
    runs-on: ubuntu-latest

    concurrency:
      group: ci

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4.0.1
      - run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Type check
        run: yarn type:check

      - name: Format check
        run: yarn format:check

      - name: Lint check
        run: yarn lint:check

      - name: Spell check
        run: yarn spell:check

      - name: Test
        run: yarn test
        env:
          INTEGRATION_TEST_USER_MNEMONIC: ${{ secrets.INTEGRATION_TEST_USER_MNEMONIC }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
