name: farcaster

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - beta

jobs:
  farcaster:
    runs-on: ubuntu-latest

    concurrency:
      group: ci

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4.0.1

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn --frozen-lockfile

      - name: Build
        run: yarn workspaces foreach --all run build

      - name: Type check
        run: yarn type:check

      - name: Lint check
        run: yarn lint:check

      - name: Spell check
        run: yarn spell:check

      - name: Check for unstaged changes to generated code
        run: yarn workspaces foreach --all run generate && git diff --exit-code

      - name: Test
        run: yarn workspaces foreach --all run test
        env:
          INTEGRATION_TEST_NEYNAR_API_KEY: ${{ secrets.INTEGRATION_TEST_NEYNAR_API_KEY }}
          INTEGRATION_TEST_NEYNAR_SIGNER_UUID: ${{ secrets.INTEGRATION_TEST_NEYNAR_SIGNER_UUID }}
          INTEGRATION_TEST_NEYNAR_SIGNER_PUBLIC_KEY: ${{ secrets.INTEGRATION_TEST_NEYNAR_SIGNER_PUBLIC_KEY }}
          INTEGRATION_TEST_NEYNAR_SIGNER_FID: ${{ secrets.INTEGRATION_TEST_NEYNAR_SIGNER_FID }}

      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npx semantic-release
